FROM node:14

# Install Docker CLI
RUN curl -fsSL https://get.docker.com -o get-docker.sh \
  && sh get-docker.sh \
  && rm get-docker.sh

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
