version: '3.8'

services:
  api-wrapper:
    build:
      context: .
      dockerfile: Dockerfile.api-wrapper
    ports:
      - "8084:3000"
    networks:
      - wappalyzer-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  wappalyzer-network:
    driver: bridge